python.exe: can't open file '\\\\wsl.localhost\\Ubuntu\\mnt\\c\\Users\\Shaun Padrejuan\\Documents\\GitHub\\LabExercise3\\scripts\\customer_remove_faultydate.py': [Errno 13] Permission denied
